app:
  debug: true
  shutdown_timeout: 22s
http:
  serve_address: localhost:8080
  base_path: /
  offering_address: "offering:8081"
socket:
  serve_address: :54321
  base_path: /
mongo:
  uri: mongodb://localhost:27017
connection:
  inbound :
    topic : "trip_inbound"
    brokers : ["kafka:29092"]
  outbound :
    topic : "trip_outbound"
    brokers :  ["kafka:29092"]