version: '3.1'
services:
  build:
    image: build:develop
    build:
      context: "."
      dockerfile: ".docker/build.Dockerfile"

  offering:
    build:
      context: "."
      dockerfile: ".docker/app.Dockerfile"
    restart: unless-stopped
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - './.config/app.docker.yaml:/app/config.yaml'
    ports:
      - "8080:8080"