version: '3.1'
services:
  build:
    image: build:develop
    build:
      context: "."
      dockerfile: ".docker/build.Dockerfile"

  client:
    build:
      context: "."
      dockerfile: ".docker/app.Dockerfile"
    restart: unless-stopped
    depends_on:
      build:
        condition: service_completed_successfully
      mongodb:
        condition: service_started
    volumes:
      - './.config/app.docker.yaml:/app/config.yaml'
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db