-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS finished_trips
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trip_id  VARCHAR(255) NOT NULL,
    offer_id VARCHAR(255) NOT NULL,
    driver_id VARCHAR(255) NOT NULL,
    successful BOOLEAN NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS finished_trips
-- +goose StatementEnd
